name: fluidpay
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  http: 0.13.1
  json_annotation: 4.0.1

dev_dependencies:
  pedantic: 1.11.0
  test: 1.16.8
  build_runner: 1.12.2
  json_serializable: 4.1.0
