name: fluidpay
# version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: 4.0.1

  dcrypto:
    git:
      url: git@github.com:PumpkinSeed/dcrypto
      ref: v0.3.0

dev_dependencies:
  pedantic: 1.11.0
  test: 1.16.8
  build_runner: 1.12.2
  json_serializable: 4.1.0
