name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/ssh-action@v0.1.6
        with:
          key: ${{ secrets.SSH_KEY }}
      - uses: dart-lang/setup-dart@v1.3
      - name: Pull dependencies
        run: dart pub get
      - name: Run tests
        run: dart pub run test
