name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dart
        uses: cedx/setup-dart@v2
      - name: Pull dependencies
        run: pub get
      - name: Build generated source
        run: pub run build_runner build
      - name: Run tests
        run: pub run test
