name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - name: Pull dependencies
        run: dart pub get
      - name: Build generated source
        run: dart pub run build_runner build
      - name: Run tests
        run: dart pub run test
