name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shimataro/ssh-key-action@v2
        with:
          name: id_rsa
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: dart-lang/setup-dart@v1.3
      - name: Pull dependencies
        run: dart pub get
      - name: Run tests
        run: dart pub run test
